### ISSUE TITLE
[FEATURE] Initial Frontend and Server Projects

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-project#1]
# Description

To start development, decision has to be taken, which frameworks, versions, etc. should be used. Once the decision is done, the initial projects shall be created and pushed to the respective repositories.

# Tasks

- [x] Technology decisions (frontend, server, db)
- [x] Initial Frontend Project Created and Available in Frontend Repo
- [x] Initial Server Project Created and Available in Server Repo

**Comment by TS-Daniel16** [comment]
Decision for mono repo, so frontend and server repo are the same
UI connects to nestJS server which reads and writes data through TypeORM to DB (currently SQLite, will be adjusted later)
